name: instagram_ui_clone
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.7.0
  provider: ^6.0.5
  google_fonts: ^4.0.3
  http: ^0.13.5
  flutter_custom_tab_bar: ^1.2.1
  contained_tab_bar_view: ^0.8.0
  bottom_bar_matu: ^1.3.0
  dropdown_button2: ^2.0.0
  image_picker: ^0.8.7+1
  rotated_corner_decoration: ^2.1.0+1
  curved_navigation_bar: ^1.0.3
  flutter_staggered_animations: ^1.1.1
  wave_transition: ^0.0.6
  intl: ^0.17.0
  audioplayers: ^4.0.1
  faker: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ic_post.png
    - assets/icon_add_post.png
    - assets/icon_logo_instagram.png
    - assets/icon_messenger.png
    - assets/pic_user_1.jpg
    - assets/pic_user_2.jpg
    - assets/pic_user_3.jpg
    - assets/pic_user_4.jpg
    - assets/icon_nav_home.png
    - assets/icon_nav_like.png
    - assets/icon_nav_reel.png
    - assets/icon_nav_search.png
    - assets/circle_menu.png
    - assets/icon_like.png
    - assets/icon_comment.png
    - assets/icon_send.png
    - assets/ic_save.png
    - assets/nav_home_ic.png
    - assets/nav_rels_ic.png
    - assets/nav_search_ic.png
    - assets/nav_shop_ic.png


        
